sudo: required
dist: xenial

stages:
  - test
  - deploy

language: node_js
node_js: 8

env:
  - HAXE_VERSION=stable
  - HAXE_VERSION=latest
  - HAXE_VERSION=nightly
  
install:
  - npm i -g lix
  - lix install haxe $HAXE_VERSION
  - lix download

script:
  - if [ "$HAXE_VERSION" != "stable" ]; then lix run travix java -D jvm; fi
  - if [ "$HAXE_VERSION" != "stable" ]; then lix run travix java -D concurrent -D jvm; fi
  - lix run travix interp
  - lix run travix neko
  - lix run travix neko -D concurrent
  - lix run travix python
  - lix run travix node
  # - lix run travix flash
  - lix run travix cpp
  - lix run travix cpp -D concurrent
  - lix run travix cs
  - lix run travix php

jobs:
  include:
    # - stage: test # should uncomment this when there is no matrix above (e.g. only one os, one env, etc)
    - stage: deploy
      os: linux
      install:
        - npm i -g lix
        - lix download
      script: skip
      env:
        secure: "boN+Z6E2oCVQn8o0P89i3D7RMuNQpzizc34HH7lCnAqO89U0cID0vaHqhLy32s3X3VKJ0VGtMHutNfpXM9NbLaPL//ZNFw5kkrmlVHGBdlYH1Jr3it8UpWq/fie/POhXmYM3Li6uUb1zfrVKCp6w7UaJck7uDLHsyYm+QSVoKpw="
      after_success:
        - lix run travix install
        - lix run travix release  